apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server-deployment
  labels:
    app: spark-history-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      labels:
        app: spark-history-server
    spec:
      containers:
        - name: spark-history-server
          image: mlobo/spark-base:v3.3.0
          args: [ "/bin/bash", "-c", "$SPARK_HOME/sbin/start-history-server.sh && tail -f $SPARK_HOME/logs/*" ]
          ports:
            - containerPort: 18080
---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-server-service
spec:
  type: NodePort
  selector:
    app: spark-history-server
  ports:
    - port: 80
      targetPort: 18080

